/**
 * Thumbnail source per route (Cloudinary public ID or legacy /images/... path).
 * Used by search index only — keep in sync when adding major pages.
 */
export const SEARCH_PAGE_IMAGES = {
  "/": "/images/Home/Background.webp",
  "/nomads-gallery": "Assets/Gallery-Tile",
  "/contact-us": "/images/Adventures/AdventuresBD.webp",
  "/nomads-shop": "/images/Adventures/AdventuresBD.webp",
  "/nomads-shop/brazil": "/images/Adventures/BrazilFlag.webp",
  "/nomads-shop/brazil/saopaulo": "Brazil/Sao Paulo/Landing/small/street",
  "/nomads-shop/brazil/rio": "Brazil/Rio/small/Rio1",
  "/nomads-shop/brazil/salvador": "Brazil/Salvador/small/Salvador5",
  "/nomads-shop/brazil/pantanal": "Brazil/Pantanal/small/Pantanal2",
  "/nomads-shop/brazil/foz": "Brazil/Iguazu/small/Iguazu16",
  "/nomads-shop/brazil/bonito": "Brazil/Bonito/Small/Bonito3",
  "/nomads-shop/brazil/manaus": "Brazil/Manaus/small/Manaus13",
  "/brazil": "Brazil/Brazil-hero",
  "/brazil/rio": "Brazil/Rio/small/Rio9",
  "/brazil/saopaulo": "Brazil/Sao Paulo/Landing/small/street",
  "/brazil/saopaulo/green-spaces": "Brazil/Sao Paulo/Green Spaces/green-spaces-backup",
  "/brazil/saopaulo/galleries": "Brazil/Sao Paulo/Galleries/Galleries-backup",
  "/brazil/saopaulo/carnival": "Brazil/Sao Paulo/Carnival/carnival-backup",
  "/brazil/saopaulo/street-art": "Brazil/Sao Paulo/Street Art/small/Graffiti2",
  "/brazil/santos": "Brazil/Santos/small/Santos3",
  "/brazil/salvador": "Brazil/Salvador/small/Salvador5",
  "/brazil/pantanal": "Brazil/Pantanal/small/Pantanal5",
  "/brazil/florianopolis": "Brazil/Floripa/small/Floripa18",
  "/brazil/foz": "Brazil/Iguazu/small/Iguazu16",
  "/brazil/manaus": "Brazil/Manaus/small/Manaus13",
  "/brazil/rio/ilha-grande": "Brazil/IlhaGrande/Small/Ilha20new",
  "/brazil/food-drink": "Brazil/Food-Drink/Small/Moqueca Lunch with Caipirinha",
  "/brazil/natural-spaces": "Brazil/Natural Spaces/small/Mata Atlântica",
  "/brazil/bonito": "Brazil/Bonito/thumbnail/Bonito7",
  "/belgium": "/images/Belgium/Antwerp/Small/Grote Markt.webp",
  "/belgium/antwerp": "Belgium/Antwerp/Full/Grote Markt",
  "/greece": "/images/Greece/Athens/Small/Acropolis Hill.webp",
  "/greece/athens": "Greece/Athens/Small/Acropolis Hill",
  "/hungary": "/images/Hungary/Budapest/Small/Parliament.webp",
  "/hungary/budapest": "Hungary/Budapest/Small/Chain Bridge",
  "/austria": "/images/Adventures/AustriaFlag.webp",
  "/austria/vienna": "Austria/Vienna-backup",
  "/austria/salzburg": "Austria/Salzburg-backup",
  "/austria/wider-country": "Austria/Wider-Country-backup",
  "/united-states": "/images/Adventures/USAFlag.webp",
  "/united-states/tennessee": "United States/Tennessee/Memphis/Small/Illuminated Beale Street",
  "/united-states/tennessee/mountains": "United States/Tennessee/Mountains/Small/Mountains1",
  "/united-states/tennessee/memphis": "United States/Tennessee/Memphis/Small/Illuminated Beale Street",
  "/united-states/tennessee/nashville": "United States/Tennessee/Nashville/Small/Nashville1",
};
