/**
 * Upgrade Brazil Tier B mobile LCP shells to Tier A (inline data URI + deferred boot).
 * Run: node scripts/upgradeBrazilTierB.cjs
 * Then: npm run optimize:brazil-hero && ... (all 11) && npm run build
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const PAGES = [
  { slug: 'brazil', shell: 'brazilStaticShell.js', constKey: 'BRAZIL_HERO_DATA_URI' },
  { slug: 'saopaulo', shell: 'saopauloStaticShell.js', constKey: 'SAO_PAULO_HERO_DATA_URI' },
  { slug: 'florianopolis', shell: 'florianopolisStaticShell.js', constKey: 'FLORIANOPOLIS_HERO_DATA_URI' },
  { slug: 'rio', shell: 'rioStaticShell.js', constKey: 'RIO_HERO_DATA_URI' },
  { slug: 'santos', shell: 'santosStaticShell.js', constKey: 'SANTOS_HERO_DATA_URI' },
  { slug: 'pantanal', shell: 'pantanalStaticShell.js', constKey: 'PANTANAL_HERO_DATA_URI' },
  { slug: 'bonito', shell: 'bonitoStaticShell.js', constKey: 'BONITO_HERO_DATA_URI' },
  { slug: 'manaus', shell: 'manausStaticShell.js', constKey: 'MANAUS_HERO_DATA_URI' },
  { slug: 'salvador', shell: 'salvadorStaticShell.js', constKey: 'SALVADOR_HERO_DATA_URI' },
  { slug: 'foz', shell: 'fozStaticShell.js', constKey: 'FOZ_HERO_DATA_URI' },
  { slug: 'food-drink', shell: 'foodDrinkStaticShell.js', constKey: 'FOOD_DRINK_HERO_DATA_URI' },
];

function patchOptimizeScript(slug, constKey) {
  const file = path.join(__dirname, `optimize-${slug}-hero.js`);
  let src = fs.readFileSync(file, 'utf8');
  if (src.includes(constKey) && src.includes('INLINE_OUT')) {
    console.log('optimize already patched', slug);
    return;
  }
  if (!src.includes('INLINE_OUT')) {
    src = src.replace(
      /(const OUTPUT = path\.join\(__dirname, '\.\.\/public\/assets\/[^']+'\);)/,
      `$1\nconst INLINE_OUT = path.join(__dirname, '${slug}-hero-inline.cjs');`
    );
  }
  if (!src.includes(constKey)) {
    const insertBlock = `  const dataUri = \`data:image/webp;base64,\${webpBuffer.toString('base64')}\`;
  await fs.promises.writeFile(
    INLINE_OUT,
    '/** Generated by npm run optimize:${slug}-hero — do not edit */\\n' +
      'module.exports = { ${constKey}: ' + JSON.stringify(dataUri) + ' };\\n'
  );`;
    src = src.replace(
      /await fs\.promises\.writeFile\(OUTPUT, webpBuffer\);/,
      `await fs.promises.writeFile(OUTPUT, webpBuffer);\n${insertBlock}`
    );
  }
  fs.writeFileSync(file, src);
}

function patchStaticShell(slug, shellFile, constKey) {
  const file = path.join(__dirname, shellFile);
  let src = fs.readFileSync(file, 'utf8');
  if (src.includes(constKey)) {
    console.log('shell already patched', shellFile);
  } else {
    src = src.replace(
      /const \{ ROUTE_LCP_PRELOAD \} = require\('\.\/routeLcpPreload\.cjs'\);/,
      `const { ${constKey} } = require('./${slug}-hero-inline.cjs');`
    );
    src = src.replace(
      /const heroSrc = ROUTE_LCP_PRELOAD\['[^']+'\] \|\| '';/,
      `const heroSrc = ${constKey} || '';`
    );
    if (!src.includes('skipLcpPreload')) {
      src = src.replace(
        /module\.exports = \{\n  SHELL_STYLES,/,
        `module.exports = {\n  SHELL_STYLES,`
      );
      src = src.replace(
        /BODY_CLASS: '[^']+',\n\};/,
        (m) => m.replace('};', `  skipLcpPreload: true,\n  bootMinDelayMs: 3000,\n};`)
      );
    }
    fs.writeFileSync(file, src);
  }
}

for (const page of PAGES) {
  patchOptimizeScript(page.slug, page.constKey);
  patchStaticShell(page.slug, page.shell, page.constKey);
  console.log('patched', page.slug);
}

fs.writeFileSync(
  path.join(__dirname, 'phase4-pages.manifest.json'),
  JSON.stringify(PAGES, null, 2)
);
console.log('Done — patch optimize scripts then run all optimize:*-hero');
